services:
  db:
    image: postgis/postgis:15-3.3
    container_name: gis_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mqtt_broker
    restart: unless-stopped
    ports:
      - "${MQTT_PORT}:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  influxdb:
    image: influxdb:3-core
    container_name: influx_db
    restart: unless-stopped
    ports:
      - "${INFLUX_PORT}:8181"
    command:
      - influxdb3
      - serve
      - --node-id=${INFLUX_NODE_ID}
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
    volumes:
      - influx_data:/var/lib/influxdb3/data

volumes:
  pgdata:
  influx_data:
