services:
  db:
    image: postgis/postgis:15-3.3
    container_name: gis_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mqtt_broker
    restart: unless-stopped
    ports:
      - "${MQTT_PORT}:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config

  backend:
    build: ./backend
    container_name: backend_gis
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "3001:3001"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - MQTT_URL=mqtt://mosquitto:1883
      - INFLUX_URL=http://influxdb:8181
    depends_on:
      - db
      - mosquitto
      - influxdb

  influxdb:
    image: influxdb:3-core
    container_name: influx_db
    restart: unless-stopped
    user: "0:0"
    ports:
      - "${INFLUX_PORT}:8181"
    command:
      - influxdb3
      - serve
      - --node-id=${INFLUX_NODE_ID}
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
    volumes:
      - influx_data:/var/lib/influxdb3/data
volumes:
  pgdata:
  influx_data:
